config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :students, :teachers do
    get :subjects
  end
  resources :visitors, :teachers, :report_subjects, :reports
  namespace :reports do
    resources :subjects
  end
  get 'reports/subjects', to: 'reports#subjects'
  get 'lists/students', to: 'students#student_list'
  root 'visitors#index'
end

app/models/participation.rb
class Participation < ActiveRecord::Base
  belongs_to :student
  belongs_to :subject_item

  validates :student, :subject_item, presence: true
  validates :student, uniqueness: { scope: :subject_item }
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :subject_items, through: :participations
  has_many :participations, dependent: :destroy
  has_many :subject_item_notes, dependent: :destroy
  
  validates :first_name, :last_name, presence: true

  accepts_nested_attributes_for :subject_items

  def payment_status
    if payment == true
      'Done'
    else
      'Waiting'
    end
  end
  
end

app/models/subject_item.rb
class SubjectItem < ActiveRecord::Base
  belongs_to :teacher

  has_many :students, through: :participations
  has_many :participations, dependent: :destroy
  has_many :subject_item_notes

  validates :title, presence: true

  scope :not_assigned_or_assigned_to_teacher, -> (teacher) { where('teacher_id IS ? or teacher_id = ?', nil, teacher) }
end

app/models/subject_item_note.rb
class SubjectItemNote < ActiveRecord::Base
  belongs_to :student
  belongs_to :subject_item

  validates :student_id, :subject_item_id, presence: true

  scope :for_subject_item, -> (subject_item) { where(subject_item: subject_item) }
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  TITLES = %w(Dr. Prof. TA)
  has_many :subject_items, dependent: :nullify

  validates :first_name, :last_name, presence: true
  validates :academic_title, inclusion: { in: TITLES }, presence: true

  accepts_nested_attributes_for :subject_items
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  decent_configuration { strategy DecentExposure::StrongParametersStrategy }

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      sanitized_params = %i(
        email
        password
        password_confirmation
      )
      u.permit(sanitized_params)
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  expose(:reports)
  expose(:subject_items){ SubjectItem.includes(:teacher, :students) }
  def show
    render :subjects
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  expose(:students)
  expose(:student, attributes: :student_params)
  expose(:student_subject_items) { student.subject_items }

  def create
    if student.save
      redirect_to student_path(student), notice: I18n.t('shared.created', resource: 'Student')
    else
      render :new
    end
  end

  def update
    if student.save
      redirect_to student_path(student), notice: I18n.t('shared.updated', resource: 'Student')
    else
      render :edit
    end
  end

  def destroy
    student.destroy
    redirect_to students_path, notice: I18n.t('shared.deleted', resource: 'Student')
  end

  def student_list
    @students = Student.all
    render :student_list
  end

  def student_params
    params.require(:student).permit(:first_name, :last_name, :birthday, :payment, :payment_date)
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  expose(:teachers)
  expose(:teacher, attributes: :teacher_params)
  expose(:teacher_subject_items) { teacher.subject_items }

  def create
    if teacher.save
      redirect_to teacher_path(teacher), notice: I18n.t('shared.created', resource: 'Teacher')
    else
      render :new
    end
  end

  def update
    if teacher.save
      redirect_to teacher_path(teacher), notice: I18n.t('shared.updated', resource: 'Teacher')
    else
      render :edit
    end
  end

  def destroy
    teacher.destroy
    redirect_to teachers_path, notice: I18n.t('shared.deleted', resource: 'Teacher')
  end

  private

  def teacher_params
    params.require(:teacher).permit(:first_name, :last_name, :academic_title, subject_item_ids: [])
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def index
    render :index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def active?(*paths)
    'active' if paths.any?{ |path| current_page?(path) }
  end
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%nav.navbar-default.navbar-fixed-top
  .container-fluid
    .navbar-header
      %button.navbar-toggle{"aria-controls" => "navbar", "aria-expanded" => "true", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'RoR Workshops', root_path, class: 'navbar-brand'
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li{ class: active?(students_path) }
          = link_to t('navbar.students'), students_path
        %li{ class: active?(lists_students_path) }
          = link_to t('navbar.payments'), lists_students_path
        %li{ class: active?(teachers_path) }
          = link_to t('navbar.teachers'), teachers_path
        %li.dropdown{ class: active?(reports_subjects_path) }
          = link_to '#', class: 'dropdown-toggle', 'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-toggle' => 'dropdown', role: 'button' do
            = t('navbar.reports')
            %span.caret
          %ul.dropdown-menu
            %li{ class: active?(reports_subjects_path) }
              = link_to t('navbar.reports_subjects'), reports_subjects_path
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li
            = link_to t('navbar.logout'), destroy_user_session_path, method: :delete
        - else
          %li
            = link_to t('navbar.signin'), new_user_session_path
          %li
            = link_to t('navbar.signup'), new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : ENV['APP_NAME']
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Ror Workshops'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render template: 'layouts/_navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      .container
        .row
          .col-xs-10.col-xs-offset-1
            = breadcrumbs separator: " &raquo; "
            = yield

app/views/pages/about.html.haml
- content_for :title do
  About
%h3 About the Website
%p
  This web application was created with
  = link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/')
  from the #{link_to('RailsApps project', 'http://railsapps.github.io/')}.

app/views/reports/_subject_item.html.haml
- subject_items.each do |subject_item|
  .subject-item
  .title
    = subject_item.decorate.title_with_assigned_teacher
  %table.table.table-condensed
    %thead
      %tr
        %th.full-name= t('subjects.columns.full_name')
        %th.avg-notes= t('subjects.columns.avg_notes')
        %th= "#{t('student.columns.birthday')}:"
    %tbody
      - subject_item.students.each do |student|
        %tr
          %td= student.decorate.full_name
          %td= student.decorate.avg_notes(subject_item)
          %td= student.birthday

app/views/reports/subjects.html.haml
- breadcrumb :subjects
.subjects
  list of subjects:
  = render 'subject_item'

app/views/students/_form.html.haml
= simple_form_for student do |f|
  = f.input :first_name
  = f.input :last_name
  = f.input :birthday, as: :date, html5: true
  = f.association :subject_items, label_method: :title, value_method: :id, label: 'Subject Items', as: :check_boxes
  = link_to t('shared.back'), students_path, class: 'btn btn-default'
  = f.button :submit

app/views/students/_student.haml
%tr
  %td= student.first_name
  %td= student.last_name
  %td= student.birthday
  %td
    = link_to student_path(student), { title: t('shared.show') } do
      %button.btn.btn-default
        = fa_icon "search"
    = link_to edit_student_path(student), { title: t('shared.edit') } do
      %button.btn.btn-default
        = fa_icon "edit"
    = link_to student_path(student), { method: :delete, title: t('shared.delete') } do
      %button.btn.btn-default
        = fa_icon "times"
    = link_to student_subjects_path(student), { title: t('shared.show_subject_items') } do
      %button.btn.btn-default
        = fa_icon "list"

app/views/students/edit.html.haml
- breadcrumb :student, student
= render 'form'

app/views/students/index.html.haml
- breadcrumb :students
= link_to t('shared.add_new_item'), new_student_path, class: 'btn btn-default'
%table.table.table-condensed
  %thead
    %tr
      %th= t('student.columns.first_name')
      %th= t('student.columns.last_name')
      %th= t('student.columns.birthday')
      %th= t('shared.actions')
  %tbody
    = render students

app/views/students/new.html.haml
= render 'form'

app/views/students/show.html.haml
- breadcrumb :student, student
%table.table.table-condensed
  %tbody
    %tr
      %td= "#{t('student.columns.first_name')}:"
      %td= student.first_name
    %tr
      %td= "#{t('student.columns.last_name')}:"
      %td= student.last_name
    %tr
      %td= "#{t('student.columns.birthday')}:"
      %td= student.birthday

= link_to t('shared.back'), students_path, class: 'btn btn-default'

app/views/students/student_list.html.haml
- breadcrumb :payments
%table.table.table-condensed
  %thead
    %tr
      %th= t('student.columns.first_name')
      %th= t('student.columns.last_name')
      %th= t('student.columns.birthday')
      %th= t('student.columns.payment')
      %th= t('student.columns.payment_date')
  %tbody
    - @students.each do |student|
      %tr
      %td= student.first_name
      %td= student.last_name
      %td= student.birthday
      %td= student.payment_status
      %td= student.payment_date

app/views/students/subjects.html.haml
- breadcrumb :student_subjects, student
= student.decorate.full_name
%table.table.table-condensed
  %thead
    %tr
      %th= t('subject.title')
      %th= t('subjects.columns.avg_notes')
  %tbody
    - student_subject_items.each do |subject_item|
      %tr
        %td= subject_item.title
        %td= student.decorate.avg_notes(subject_item)
= link_to t('shared.back'), students_path, class: 'btn btn-default'

app/views/teachers/_form.html.haml
= simple_form_for teacher do |f|
  = f.input :first_name
  = f.input :last_name
  = f.input :academic_title, collection: Teacher::TITLES, include_blank: false
  = f.association :subject_items, label_method: :title, value_method: :id, label: 'Subject Items',  as: :check_boxes
  = link_to t('shared.back'), teachers_path, class: 'btn btn-default'
  = f.button :submit

app/views/teachers/_teacher.html.haml
%tr
  %td= teacher.first_name
  %td= teacher.last_name
  %td= teacher.academic_title
  %td
    = link_to teacher_path(teacher), { title: t('shared.show') } do
      %button.btn.btn-default
        = fa_icon "search"
    = link_to edit_teacher_path(teacher), { title: t('shared.edit') } do
      %button.btn.btn-default
        = fa_icon "edit"
    = link_to teacher_path(teacher), { method: :delete, title: t('shared.delete') } do
      %button.btn.btn-default
        = fa_icon "times"
    = link_to teacher_subjects_path(teacher), { title: t('shared.show_subject_items') } do
      %button.btn.btn-default
        = fa_icon "list"

app/views/teachers/edit.html.haml
- breadcrumb :teacher, teacher
= render 'form'

app/views/teachers/index.html.haml
- breadcrumb :teachers
= link_to t('shared.add_new_item'), new_teacher_path, class: 'btn btn-default'
%table.table.table-condensed
  %thead
    %tr
      %th= t('teacher.columns.first_name')
      %th= t('teacher.columns.last_name')
      %th= t('teacher.columns.academic_title')
      %th= t('shared.actions')
  %tbody
    = render teachers

app/views/teachers/new.html.haml
= render 'form'

app/views/teachers/show.html.haml
- breadcrumb :teacher, teacher
%table.table.table-condensed
  %tbody
    %tr
      %td= "#{t('teacher.columns.first_name')}:"
      %td= teacher.first_name
    %tr
      %td= "#{t('teacher.columns.last_name')}:"
      %td= teacher.last_name
    %tr
      %td= "#{t('teacher.columns.academic_title')}:"
      %td= teacher.academic_title

= link_to t('shared.back'), teachers_path, class: 'btn btn-default'

app/views/teachers/subjects.html.haml
- breadcrumb :teacher_subjects, teacher
= teacher.decorate.full_name
%table.table.table-condensed
  %thead
    %tr
      %th= t('subject.title')
  %tbody
    - teacher_subject_items.each do |subject_item|
      %tr
        %td= subject_item.title
= link_to t('shared.back'), teachers_path, class: 'btn btn-default'

app/views/visitors/index.html.haml
.bg
  .header
    School Diary Application